sync-vivaldi rewrite

diff --git a/msys2_mainHome/.bin/sync-vivaldi b/msys2_mainHome/.bin/sync-vivaldi
--- a/msys2_mainHome/.bin/sync-vivaldi
+++ b/msys2_mainHome/.bin/sync-vivaldi
@@ -1,24 +1,15 @@
 #!/usr/bin/env bash
 #vivaldi sessions sync
 
-# test arguments
-if [ $# -eq 0 ]; then
-	echo -e '\e[31mYou have to specify pull or push'
-	exit 2
-fi
-
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+# log file size
 maxsize=900000
 baksize=1000000
 # paths - change these as needed
-encoder_PCx="/d/WorkSpace/=encoder="
-encoder_x230="/d/_gitClone/[encoder]"
-vivaldiSession="$(cygpath $USERPROFILE)/AppData/Local/Vivaldi/User Data"
+vivaldiSession="$(cygpath $USERPROFILE)/AppData/Local/Vivaldi/User Data/Default/Sessions"
 dotfiles="$(cygpath $USERPROFILE)/dotfiles"
-# logfiles
-runLog="sync-vivaldi.$HOSTNAME.${1^^}.log"
-dryLog="sync-vivaldi.$HOSTNAME.${1^^}.DRY_RUN"
 # preview coloring
-grepSysCol="mt=1;93"
+grepSysCol="mt=1;93;44"
 grepSendCol="mt=1;34"
 grepDelCol="mt=1;31"
 grepUnchCol="mt=1;32"
@@ -26,49 +17,108 @@ grepSysMsg='(total:).*|(sending incremental file list)|(delta-transmission).*|.*
 grepSendMsg='^(\[sender\]).*|$'
 grepDelMsg='(deleting).*|$'
 grepUnchMsg='.*(uptodate)$|$'
+# logfiles
+runLog="$(basename $0).$HOSTNAME.log"
+dryLog="$(basename $0).$HOSTNAME.DRY_RUN"
 
-# get where we are
-if [ -d "$encoder_x230" ]; then
-	encoderGit="$encoder_x230"
-	read -p $'\e[44mDirectory \e[33m$encoder_x230\e[37m found. Using \e[33m$encoder_x230\e[37m as Git versioning. \e[35mOn the road mode...\e[0m\n' -t 5
-elif [ -d "$encoder_PCx" ]; then
-	encoderGit="$encoder_PCx"
-	read -p $'\e[44mDirectory \e[33m$encoder_PCx\e[37m found. Using \e[33m$encoder_PCx\e[37m as Git versioning. \e[35mHomebase mode...\e[0m\n' -t 5
-fi
+function usage() {
+	cat <<HELP_USAGE
 
-# MAIN logic
-if [ "$1" == 'pull' ]; then
-	rsync -Ccazvvn "$encoderGit/(Vivaldi_Sessions)/" "$vivaldiSession/Default/Sessions/" | tee $dryLog | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
-	read -p "Confirm $1? [no] " yesOrYes
-	yesOrYes=${yesOrYes:-no}
-	if [ "$yesOrYes" == 'yes' ]; then
-		rsync -Ccazv "$encoderGit/(Vivaldi_Sessions)/" "$vivaldiSession/Default/Sessions/" --log-files="$runLog"
-		cp "$runLog" "$dotfiles/.logs/"
+    usage: $(basename $0) [ps|pl]
+
+    -h, --help			Print this message
+    ps, push			Sync current directory to git repo
+    pl, pull			Sync git repo to current dir
+HELP_USAGE
+
+	exit 0
+}
+
+function check_dir() {
+	if [ ! -d "$1" ]; then
+		echo -e "\e[30;43mWARNING: directory $1 not found, exiting...\e[0m"
+		exit 1
 	fi
-elif [ "$1" == 'push' ]; then
-	rsync -Ccazvvn "$vivaldiSession/Default/Sessions/" "$encoderGit/(Vivaldi_Sessions)/" | tee $dryLog | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
-	read -p "Confirm $1? [no] " yesOrYes
-	yesOrYes=${yesOrYes:-no}
-	if [ "$yesOrYes" == 'yes' ]; then
-		rsync -Ccazv "$vivaldiSession/Default/Sessions/" "$encoderGit/(Vivaldi_Sessions)/" --log-file="$runLog"
-		cp "$runLog" "$dotfiles/.logs/"
-	fi
-fi
+}
 
-# log sizing & archiving
-filesize=$(stat -c%s "$runLog")
-if ((filesize > maxsize)) && ((filesize < baksize)); then
-	echo -e "\e[30;43mCaution: Log file is 900kb large. Consider backing up and/or deleting. Log will be automatically archived soon.\e[0m"
-elif ((filesize > baksize)); then
-	echo -e "\e[34;43mAttention: Log file is 1mb large. Archiving...\e[0m"
-	for i in {1..3}; do
-		if [ ! -f "$runLog.bak$i" ]; then
-			tar -czvf "$runLog.bak$i" "$runLog"
-			: >"$runLog"
-			echo -e "\e[34mLog file archived to $runLog.bak$i (uses tar gzip). Note that log backups are not sent to Git versioning.\e[0m"
-			break
-		elif [ -f "$runLog.bak1" ] && [ -f "$runLog.bak2" ] && [ -f "$runLog.bak3" ]; then
-			echo -e "\e[31;44mArchive full! Highly advise deleting the log files and/or backups. This message will keep showing otherwise. File $runLog.bak$i exists.\e[0m"
+function main_logic() {
+	# if [ "$1" == 'pull' ]; then
+	check_dir "$dotfiles/vivaldi_sessions"
+	check_dir "$vivaldiSession"
+	rsync -Ccazvvn "$1" "$2" | tee "$HOME/.logs/$dryLog" | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
+	read -p "Confirm $sync? [no] " yesOrYes
+	yesOrYes=${yesOrYes:-no}
+	if [ "$yesOrYes" == 'yes' ] || [ "$yesOrYes" == 'y' ]; then
+		rsync -Ccazv "$1" "$2" --log-file="$HOME/.logs/$runLog"
+		if [ -f "$dotfiles/.logs/$runLog" ] && [ -f "$HOME/.logs/$runLog" ]; then
+			diff -u $dotfiles/.logs/$runLog $HOME/.logs/$runLog | grep -E "^\+" | sed -E 's/^\+//' >>$dotfiles/.logs/$runLog
+			cp "$dotfiles/.logs/$runLog" "$HOME/.logs/"
+		else
+			cp "$HOME/.logs/$runLog" "$dotfiles/.logs/"
 		fi
+		rm "$HOME/.logs/$dryLog"
+	fi
+	# elif [ "$1" == 'push' ]; then
+	# 	rsync -Ccazvvn "$vivaldiSession/Default/Sessions/" "$encoderGit/(Vivaldi_Sessions)/" | tee $dryLog | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
+	# 	read -p "Confirm $1? [no] " yesOrYes
+	# 	yesOrYes=${yesOrYes:-no}
+	# 	if [ "$yesOrYes" == 'yes' ]; then
+	# 		rsync -Ccazv "$vivaldiSession/Default/Sessions/" "$encoderGit/(Vivaldi_Sessions)/" --log-file="$runLog"
+	# 		cp "$runLog" "$dotfiles/.logs/"
+	# 	fi
+	# fi
+}
+
+function command_param() {
+	case $1 in
+
+	pl | pull)
+		sync="pull"
+		echo -e "\e[44m${sync[@]^}ing Vivaldi sessions\e[0m"
+		main_logic "$dotfiles/vivaldi_sessions/" "$vivaldiSession/"
+		;;
+
+	ps | push)
+		sync="push"
+		echo -e "\e[44m${sync[@]^}ing Vivaldi sessions\e[0m"
+		main_logic "$vivaldiSession/" "$dotfiles/vivaldi_sessions/"
+		;;
+
+	"" | -h | --help)
+		usage
+		;;
+
+	*)
+		echo "Unknown option - $1"
+		usage
+		;;
+	esac
+}
+
+if [ $# -gt 1 ]; then
+	for ((i = 2; i <= $#; i++)); do
+		echo "No parameter ${!i} found"
 	done
+	usage
+else
+	command_param $1
+fi
+
+# log archiving
+if [ -f "$HOME/.logs/$runLog" ]; then
+	filesize=$(stat -c%s "$HOME/.logs/$runLog")
+	if ((filesize > maxsize)) && ((filesize < baksize)); then
+		echo -e "\e[30;43mCaution: Log file is 900kb large. Consider backing up and/or deleting. Log will be automatically archived soon.\e[0m"
+	elif ((filesize > baksize)); then
+		echo -e "\e[34;43mAttention: Log file is 1mb large. Archiving...\e[0m"
+		for i in {1..3}; do
+			if [ ! -f "$HOME/.logs/$runLog.bak$i" ]; then
+				tar -czvf "$HOME/.logs/$runLog.bak$i" "$HOME/.logs/$runLog" --remove-files
+				echo -e "\e[34mLog file archived to $HOME/.logs/$runLog.bak$i (uses tar gzip). Note that log backups are not sent to Git versioning.\e[0m"
+				break
+			elif [ -f "$HOME/.logs/$runLog.bak1" ] && [ -f "$HOME/.logs/$runLog.bak2" ] && [ -f "$HOME/.logs/$runLog.bak3" ]; then
+				echo -e "\e[31;44mArchive full! Highly advise deleting the log files and/or backups. This message will keep showing otherwise. File $HOME/.logs/$runLog.bak$i exists.\e[0m"
+			fi
+		done
+	fi
 fi
