WIP Rework user path definition

diff --git a/msys2_mainHome/.bin/sync-persist b/msys2_mainHome/.bin/sync-persist
--- a/msys2_mainHome/.bin/sync-persist
+++ b/msys2_mainHome/.bin/sync-persist
@@ -46,16 +46,12 @@ HELP_USAGE
 	exit 0
 }
 
-function check_dir() {
-	if [ ! -d "$1" ]; then
-		echo -e "\e[30;43mWARNING: directory $1 not found (wrong sync dir?), exiting...\e[0m"
-		exit 1
-	fi
-}
-
 function path_input() {
 	read -e -p "Please enter path to scoop: " source
-	check_dir "$source/persist/"
+	if [ ! -d "$source/persist" ]; then
+		echo -e "\e[30;43mWARNING: directory $source/persist not found (wrong sync dir?), exiting...\e[0m"
+		exit 1
+	fi
 }
 
 function define_source() {
diff --git a/msys2_mainHome/.bin/sync-profile b/msys2_mainHome/.bin/sync-profile
--- a/msys2_mainHome/.bin/sync-profile
+++ b/msys2_mainHome/.bin/sync-profile
@@ -55,16 +55,12 @@ HELP_USAGE
 	exit 0
 }
 
-function check_dir() {
-	if [ ! -d "$1" ]; then
-		echo -e "\e[30;43mWARNING: directory $1 not found (wrong sync dir?), exiting...\e[0m"
-		exit 1
-	fi
-}
-
 function path_input() {
 	read -e -p "Please enter path to profile: " source
-	check_dir "$source/"
+	if [ ! -f "$source/$2" ]; then
+		echo -e "\e[30;43mWARNING: file $source/$2 not found (wrong sync dir?), exiting...\e[0m"
+		exit 1
+	fi
 }
 
 function define_source() {
@@ -77,7 +73,7 @@ function define_source() {
 		read -p $'\e[44mProfile found on \e[33m'"$source"$'\e[0m\n' -t 5
 	else
 		echo -e "\e[31mProfile directory not found. Is it installed?\e[0m"
-		path_input
+		path_input $2
 	fi
 }
 
@@ -127,11 +123,11 @@ function command_param() {
 	case $2 in
 
 	pwsh | powershell)
-		define_source "$pwshProfile"
+		define_source "$pwshProfile" "profile.ps1"
 		echo -e "\e[44m${sync[@]^}ing Powershell Core profile\e[0m"
 		if [ "$sync" == "pull" ]; then
 			main_logic "$dotfiles/$dotfilesDirPWSH/" "$source/"
-			define_source "$powershellProfile"
+			define_source "$powershellProfile" "profile.ps1"
 			echo -e "\e[44m${sync[@]^}ing Powershell profile\e[0m"
 			main_logic "$dotfiles/$dotfilesDirPWSH/" "$source/"
 		elif [ "$sync" == "push" ]; then
@@ -141,7 +137,7 @@ function command_param() {
 		;;
 
 	term | terminal | winterminal)
-		define_source "$terminalProfile"
+		define_source "$terminalProfile" "profiles.json"
 		echo -e "\e[44m${sync[@]^}""ing terminal profile\e[0m"
 		if [ "$sync" == "pull" ]; then
 			main_logic "$dotfiles/$dotfilesDirTERM/" "$source/"
@@ -151,7 +147,7 @@ function command_param() {
 		;;
 
 	msys | msys2 | bash)
-		define_source
+		define_source "$HOME" ".bash_profile"
 		echo -e "\e[44m${sync[@]^}""ing MSYS2 profile\e[0m"
 		if [ "$sync" == "pull" ]; then
 			main_logic "$dotfiles/$dotfilesDirMSYS/" "$HOME/"
