sync calibre & profile revision: added dir exist check

diff --git a/msys2_mainHome/.bin/sync-calibre b/msys2_mainHome/.bin/sync-calibre
--- a/msys2_mainHome/.bin/sync-calibre
+++ b/msys2_mainHome/.bin/sync-calibre
@@ -77,12 +77,14 @@ function main_logic() {
 }
 
 function define_source() {
-	if [ "$(whoami)" == "zeruel" ]; then
+	if [ -d $calibre_PCx ]; then
 		source="$calibre_PCx"
-	elif [ "$(whoami)" == "zeruel11" ]; then
+		read -p $'\e[44mDirectory \e[33m$calibre_PCx\e[37m found. \e[35mHomebase mode...\e[0m\n' -t 5
+	elif [ -d $calibre_x230 ]; then
 		source="$calibre_x230"
+		read -p $'\e[44mDirectory \e[33m$calibre_x230\e[37m found. \e[35mOn the road mode...\e[0m\n' -t 5
 	else
-		echo "Nowhere"
+		echo -e "Youre neither at your pc nor your laptop... \e[31mWho or where the fluff are you?!\e[0m"
 		exit 0
 	fi
 }
@@ -153,6 +155,10 @@ if [ $# -gt 2 ]; then
 	done
 	usage
 else
+	if [ ! -d $dotfiles ]; then
+		echo -e "\e[31mDotfiles dir $dotfiles not found. Misplaced?\e[0m"
+		exit 1
+	fi
 	define_source
 	command_param $1 $2
 fi
diff --git a/msys2_mainHome/.bin/sync-profile b/msys2_mainHome/.bin/sync-profile
--- a/msys2_mainHome/.bin/sync-profile
+++ b/msys2_mainHome/.bin/sync-profile
@@ -53,9 +53,9 @@ HELP_USAGE
 }
 
 function check_dir() {
-	if [ ! -d $1 ] ; then
-	echo -e "\e[30;43mWARNING: directory $1 not found, exiting...\e[0m"
-	exit 1
+	if [ ! -d $1 ]; then
+		echo -e "\e[30;43mWARNING: directory $1 not found, exiting...\e[0m"
+		exit 1
 	fi
 }
 
@@ -65,7 +65,8 @@ function main_logic() {
 	# if [ "$DIFF" != "" ]; then
 	# 	echo "The directory was modified"
 	# fi
-	check_dir $1; check_dir $2
+	check_dir $1
+	check_dir $2
 	rsync -Ccazvvn --existing --filter="merge $filterFile" "$1" "$2" | tee "$HOME/.logs/$dryLog" | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepSkipCol" egrep --color=always "$grepSkipMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
 	read -p "Confirm $sync? [no] " yesOrYes
 	yesOrYes=${yesOrYes:-no}
@@ -151,6 +152,10 @@ if [ $# -gt 2 ]; then
 	done
 	usage
 else
+	if [ ! -d $dotfiles ]; then
+		echo -e "\e[31mDotfiles dir $dotfiles not found. Misplaced?\e[0m"
+		exit 1
+	fi
 	command_param $1 $2
 fi
 
