Make dotfiles mandatory for all sync
Dotfiles folder presence are now enforced on the following scripts:
- sync-calibre
- sync-persist
- sync-profile
- sync-vivaldi

This approach was taken so that logs dont get unecessary desynchronized
and to streamline outstanding sync scripts that needs multiple folder
present. This also comes as consequence to user input, WIP new methods
for ensuring user provides correct paths sync to work as intended.

diff --git a/msys2_mainHome/.bin/sync-calibre b/msys2_mainHome/.bin/sync-calibre
--- a/msys2_mainHome/.bin/sync-calibre
+++ b/msys2_mainHome/.bin/sync-calibre
@@ -49,6 +49,35 @@ HELP_USAGE
 	exit 0
 }
 
+function check_dir() {
+	if [ ! -d "$1" ]; then
+		echo -e "\e[30;43mWARNING: directory $1 not found (wrong sync dir?), exiting...\e[0m"
+		exit 1
+	fi
+}
+
+function path_input() {
+	read -e -p "Please enter path to calibre: " source
+	check_dir "$source/"
+}
+
+function define_source() {
+	if [ ! -d "$dotfiles" ]; then
+		echo -e "\e[30;43mWARNING: $dotfiles not found, exiting...\e[0m"
+		exit 1
+	fi
+	if [ -d "$calibre_PCx" ]; then
+		source="$calibre_PCx"
+		read -p $'\e[44mCalibre catalogue found on \e[33m'"$source"$'\e[0m\n' -t 5
+	elif [ -d "$calibre_x230" ]; then
+		source="$calibre_x230"
+		read -p $'\e[44mCalibre catalogue found on \e[33m'"$source"$'\e[0m\n' -t 5
+	else
+		echo -e "\e[31mCalibre catalogue directory not found. Is it installed?\e[0m"
+		path_input
+	fi
+}
+
 # check IKTI online
 function IKTIonline() {
 	if ssh IKTI "[ -d "$rsyncTest" ]"; then
@@ -56,19 +85,6 @@ function IKTIonline() {
 	else
 		echo -e "\e[41mServer is unreachable\e[0m"
 		exit 1
-	fi
-}
-
-function define_source() {
-	if [ -d "$calibre_PCx" ]; then
-		source="$calibre_PCx"
-		read -p $'\e[44mDirectory \e[33m$calibre_PCx\e[37m found. \e[35mHomebase mode...\e[0m\n' -t 5
-	elif [ -d "$calibre_x230" ]; then
-		source="$calibre_x230"
-		read -p $'\e[44mDirectory \e[33m$calibre_x230\e[37m found. \e[35mOn the road mode...\e[0m\n' -t 5
-	else
-		echo -e "Youre neither at your pc nor your laptop... \e[31mWho or where the fluff are you?!\e[0m"
-		exit 0
 	fi
 }
 
@@ -86,16 +102,16 @@ function main_logic() {
 	if [ "$yesOrYes" == 'yes' -o "$yesOrYes" == 'y' ]; then
 		echo "$1 $sync to $2" >>$HOME/.logs/$runLog
 		rsync -Cuazv --exclude-from="$filterFile" "$1" "$2" $3 --log-file="$runLog"
-		if [ -d $dotfiles ]; then
-			if [ -f "$dotfiles/.logs/$runLog" ] && [ -f "$HOME/.logs/$runLog" ]; then
-				diff -u $dotfiles/.logs/$runLog $HOME/.logs/$runLog | grep -E "^\+" | sed -E 's/^\+//' >>$dotfiles/.logs/$runLog
-				cp "$dotfiles/.logs/$runLog" "$HOME/.logs/"
-			else
-				cp "$HOME/.logs/$runLog" "$dotfiles/.logs/"
-			fi
+		# if [ -d $dotfiles ]; then
+		if [ -f "$dotfiles/.logs/$runLog" ] && [ -f "$HOME/.logs/$runLog" ]; then
+			diff -u $dotfiles/.logs/$runLog $HOME/.logs/$runLog | grep -E "^\+" | sed -E 's/^\+//' >>$dotfiles/.logs/$runLog
+			cp "$dotfiles/.logs/$runLog" "$HOME/.logs/"
 		else
-			echo -e "\e[30;43mWARNING: directory $dotfiles not found, logfiles will NOT be synced\e[0m"
+			cp "$HOME/.logs/$runLog" "$dotfiles/.logs/"
 		fi
+		# else
+		# 	echo -e "\e[30;43mWARNING: directory $dotfiles not found, logfiles will NOT be synced\e[0m"
+		# fi
 		rm "$HOME/.logs/$dryLog"
 	fi
 }
@@ -106,25 +122,25 @@ function command_param() {
 	pl | pull)
 		sync="pull"
 		command_exception "$2"
-		echo -e "\e[44m${sync[@]^}ing Calibre e-book catalogue\e[0m"
 		define_source
 		IKTIonline
+		echo -e "\e[44m${sync[@]^}ing Calibre e-book catalogue\e[0m"
 		main_logic "$calibre_IKTI" "$source/"
 		;;
 
 	ps | push)
 		sync="push"
 		command_exception "$2"
-		echo -e "\e[44m${sync[@]^}ing Calibre e-book catalogue\e[0m"
 		define_source
 		IKTIonline
+		echo -e "\e[44m${sync[@]^}ing Calibre e-book catalogue\e[0m"
 		main_logic "$source/" "$calibre_IKTI" "--delete-before --delete-excluded"
 		;;
 
 	ex | export)
 		sync="export"
-		echo -e "\e[44m${sync[@]^}ing Calibre e-book catalogue\e[0m"
 		define_source
+		echo -e "\e[44m${sync[@]^}ing Calibre e-book catalogue\e[0m"
 		if [ $# -lt 2 ]; then
 			echo "Path not specified, using default: $FD"
 			if [ -d "$FD" ]; then
@@ -153,7 +169,7 @@ function command_param() {
 	"")
 		usage
 		;;
-		
+
 	*)
 		echo "Unknown option - $1"
 		usage
diff --git a/msys2_mainHome/.bin/sync-persist b/msys2_mainHome/.bin/sync-persist
--- a/msys2_mainHome/.bin/sync-persist
+++ b/msys2_mainHome/.bin/sync-persist
@@ -59,12 +59,16 @@ function path_input() {
 }
 
 function define_source() {
+	if [ ! -d "$dotfiles" ]; then
+		echo -e "\e[30;43mWARNING: $dotfiles not found, exiting...\e[0m"
+		exit 1
+	fi
 	if [ -d "$scoopScoopy" ]; then
-		read -p $'\e[44mScoop directory found on '"$scoopScoopy"$'\e[0m\n' -t 5
 		source="$scoopScoopy"
+		read -p $'\e[44mScoop directory found on '"$source"$'\e[0m\n' -t 5
 	elif [ -d "$scoopDefault" ]; then
-		read -p $'\e[44mScoop default install directory found on '"$scoopScoopy"$'\e[0m\n' -t 5
 		source="$scoopDefault"
+		read -p $'\e[44mScoop directory found on '"$source"$'\e[0m\n' -t 5
 	else
 		echo -e "\e[31mScoop install directory not found. Is it installed?\e[0m"
 		path_input
@@ -72,22 +76,21 @@ function define_source() {
 }
 
 function main_logic() {
-	check_dir "$dotfiles/$dotfilesDir"
 	rsync -Ccazvvn --filter="merge $filterFile" "$1" "$2" | tee "$HOME/.logs/$dryLog" | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepSkipCol" egrep --color=always "$grepSkipMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
 	read -p "Confirm $sync? [no] " yesOrYes
 	if [ "$yesOrYes" == 'yes' -o "$yesOrYes" == 'y' ]; then
 		echo "$1 $sync to $2" >>$HOME/.logs/$runLog
 		rsync -Cuazv --filter="merge $filterFile" "$1" "$2" --log-file="$runLog"
-		if [ -d $dotfiles ]; then
-			if [ -f "$dotfiles/.logs/$runLog" ] && [ -f "$HOME/.logs/$runLog" ]; then
-				diff -u $dotfiles/.logs/$runLog $HOME/.logs/$runLog | grep -E "^\+" | sed -E 's/^\+//' >>$dotfiles/.logs/$runLog
-				cp "$dotfiles/.logs/$runLog" "$HOME/.logs/"
-			else
-				cp "$HOME/.logs/$runLog" "$dotfiles/.logs/"
-			fi
+		# if [ -d $dotfiles ]; then
+		if [ -f "$dotfiles/.logs/$runLog" ] && [ -f "$HOME/.logs/$runLog" ]; then
+			diff -u $dotfiles/.logs/$runLog $HOME/.logs/$runLog | grep -E "^\+" | sed -E 's/^\+//' >>$dotfiles/.logs/$runLog
+			cp "$dotfiles/.logs/$runLog" "$HOME/.logs/"
 		else
-			echo -e "\e[30;43mWARNING: directory $dotfiles not found, logfiles will NOT be synced\e[0m"
+			cp "$HOME/.logs/$runLog" "$dotfiles/.logs/"
 		fi
+		# else
+		# 	echo -e "\e[30;43mWARNING: directory $dotfiles not found, logfiles will NOT be synced\e[0m"
+		# fi
 		rm "$HOME/.logs/$dryLog"
 	fi
 }
diff --git a/msys2_mainHome/.bin/sync-profile b/msys2_mainHome/.bin/sync-profile
--- a/msys2_mainHome/.bin/sync-profile
+++ b/msys2_mainHome/.bin/sync-profile
@@ -6,10 +6,13 @@ DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 maxsize=900000
 baksize=1000000
 # paths
-terminalProfile="$(cygpath $LOCALAPPDATA)/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
 pwshProfile="$(cygpath $USERPROFILE)/Documents/PowerShell"
 powershellProfile="$(cygpath $USERPROFILE)/Documents/WindowsPowerShell"
+terminalProfile="$(cygpath $LOCALAPPDATA)/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
 dotfiles="$(cygpath $USERPROFILE)/dotfiles"
+dotfilesDirPWSH="win10_userprofile/powershell"
+dotfilesDirTERM="win10_userprofile/win_terminal"
+dotfilesDirMSYS="msys2_mainHome"
 # preview coloring
 grepSysCol="mt=1;93;44"
 grepSendCol="mt=1;34"
@@ -54,8 +57,27 @@ HELP_USAGE
 
 function check_dir() {
 	if [ ! -d "$1" ]; then
-		echo -e "\e[30;43mWARNING: directory $1 not found, exiting...\e[0m"
+		echo -e "\e[30;43mWARNING: directory $1 not found (wrong sync dir?), exiting...\e[0m"
 		exit 1
+	fi
+}
+
+function path_input() {
+	read -e -p "Please enter path to profile: " source
+	check_dir "$source/"
+}
+
+function define_source() {
+	if [ ! -d "$dotfiles" ]; then
+		echo -e "\e[30;43mWARNING: $dotfiles not found, exiting...\e[0m"
+		exit 1
+	fi
+	if [ -d "$1" ]; then
+		source="$1"
+		read -p $'\e[44mProfile found on \e[33m'"$source"$'\e[0m\n' -t 5
+	else
+		echo -e "\e[31mProfile directory not found. Is it installed?\e[0m"
+		path_input
 	fi
 }
 
@@ -65,8 +87,6 @@ function main_logic() {
 	# if [ "$DIFF" != "" ]; then
 	# 	echo "The directory was modified"
 	# fi
-	check_dir "$1"
-	check_dir "$2"
 	rsync -Ccazvvn --existing --filter="merge $filterFile" "$1" "$2" | tee "$HOME/.logs/$dryLog" | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepSkipCol" egrep --color=always "$grepSkipMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
 	read -p "Confirm $sync? [no] " yesOrYes
 	yesOrYes=${yesOrYes:-no}
@@ -107,32 +127,36 @@ function command_param() {
 	case $2 in
 
 	pwsh | powershell)
+		define_source "$pwshProfile"
 		echo -e "\e[44m${sync[@]^}ing Powershell Core profile\e[0m"
 		if [ "$sync" == "pull" ]; then
-			main_logic "$dotfiles/win10_userprofile/powershell/" "$pwshProfile/"
+			main_logic "$dotfiles/$dotfilesDirPWSH/" "$source/"
+			define_source "$powershellProfile"
 			echo -e "\e[44m${sync[@]^}ing Powershell profile\e[0m"
-			main_logic "$dotfiles/win10_userprofile/powershell/" "$powershellProfile/"
+			main_logic "$dotfiles/$dotfilesDirPWSH/" "$source/"
 		elif [ "$sync" == "push" ]; then
-			main_logic "$pwshProfile/" "$dotfiles/win10_userprofile/powershell/"
+			main_logic "$source/" "$dotfiles/$dotfilesDirPWSH/"
 			echo -e "\e[43mNot pushing Windows Powershell profile (this should follow pwsh)\e[0m"
 		fi
 		;;
 
 	term | terminal | winterminal)
+		define_source "$terminalProfile"
 		echo -e "\e[44m${sync[@]^}""ing terminal profile\e[0m"
 		if [ "$sync" == "pull" ]; then
-			main_logic "$dotfiles/win10_userprofile/win_terminal/" "$terminalProfile/"
+			main_logic "$dotfiles/$dotfilesDirTERM/" "$source/"
 		elif [ "$sync" == "push" ]; then
-			main_logic "$terminalProfile/" "$dotfiles/win10_userprofile/win_terminal/"
+			main_logic "$source/" "$dotfiles/$dotfilesDirTERM/"
 		fi
 		;;
 
 	msys | msys2 | bash)
+		define_source
 		echo -e "\e[44m${sync[@]^}""ing MSYS2 profile\e[0m"
 		if [ "$sync" == "pull" ]; then
-			main_logic "$dotfiles/msys2_mainHome/" "$HOME/"
+			main_logic "$dotfiles/$dotfilesDirMSYS/" "$HOME/"
 		elif [ "$sync" == "push" ]; then
-			main_logic "$HOME/" "$dotfiles/msys2_mainHome/"
+			main_logic "$HOME/" "$dotfiles/$dotfilesDirMSYS/"
 		fi
 		;;
 
diff --git a/msys2_mainHome/.bin/sync-vivaldi b/msys2_mainHome/.bin/sync-vivaldi
--- a/msys2_mainHome/.bin/sync-vivaldi
+++ b/msys2_mainHome/.bin/sync-vivaldi
@@ -48,6 +48,10 @@ function path_input() {
 }
 
 function define_source() {
+	if [ ! -d "$dotfiles" ]; then
+		echo -e "\e[30;43mWARNING: $dotfiles not found, exiting...\e[0m"
+		exit 1
+	fi
 	if [ -d "$vivaldiSession" ]; then
 		read -p $'\e[44mVivaldi session directory found on '"$vivaldiSession"$'\e[0m\n' -t 5
 		source="$vivaldiSession"
@@ -58,7 +62,6 @@ function define_source() {
 }
 
 function main_logic() {
-	check_dir "$dotfiles/$dotfilesDir"
 	rsync -Ccazvvn "$1" "$2" | tee "$HOME/.logs/$dryLog" | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
 	read -p "Confirm $sync? [no] " yesOrYes
 	yesOrYes=${yesOrYes:-no}
